[project]
name = "turban-toolbox"
dynamic = ["version"]
description = "Turbulence Analysis Toolbox"
authors = [
  { name = "Achim Randelhoff", email = "ara@akvaplan.niva.no" },
  { name = "Peter Holtermann", email = "peter.holtermann@iow.de" },
]
license = { text = "GPLv03" }
dependencies = [
  'beartype',
  'gsw',
  'jaxtyping',
  'matplotlib',
  'netCDF4',
  'numba',
  'numpy',
  'pandas',
  'pydantic',
  'scipy',
  'setuptools',
  'xarray',
] # for end user only - for developers, see environment-dev.yml
requires-python = ">=3.9"
readme = "README.md"
classifiers = [
  'Development Status :: 4 - Beta',
  'Topic :: Scientific/Engineering',
  'Intended Audience :: Science/Research',
  'License :: OSI Approved :: GNU General Public License v3 (GPLv3)',
  'Operating System :: OS Independent',
  'Programming Language :: Python :: 3 :: Only',
]

[project.scripts]


[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = false

[tool.setuptools.packages.find]

[tool.setuptools.package-data]
"*" = ["VERSION"]

[tool.pytest.ini_options]
filterwarnings = "always::UserWarning"

[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''

(
  /(
    | \.ipynb_checkpoints
    | \.pytest_cache
    | __pycache__
  )/
)

'''
